/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistrationResultRouteImport } from './routes/registrationResult'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as RegistrationShopRouteImport } from './routes/registration/shop'
import { Route as RegistrationDealershipRouteImport } from './routes/registration/dealership'
import { Route as RegistrationCompleteRouteImport } from './routes/registration/complete'
import { Route as PasswordForgotRouteImport } from './routes/password/forgot'
import { Route as AuthenticatedRepair_ordersRouteImport } from './routes/_authenticated/repair_orders'
import { Route as AuthenticatedParts_ordersRouteImport } from './routes/_authenticated/parts_orders'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedRepair_ordersIdRouteImport } from './routes/_authenticated/repair_orders/$id'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminShopsRouteImport } from './routes/_authenticated/admin/shops'
import { Route as AuthenticatedAdminParts_ordersRouteImport } from './routes/_authenticated/admin/parts_orders'
import { Route as AuthenticatedAdminDealershipsRouteImport } from './routes/_authenticated/admin/dealerships'
import { Route as PasswordResetIdGuidHashRouteImport } from './routes/password/reset/$id/$guid/$hash'

const RegistrationResultRoute = RegistrationResultRouteImport.update({
  id: '/registrationResult',
  path: '/registrationResult',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const RegistrationShopRoute = RegistrationShopRouteImport.update({
  id: '/registration/shop',
  path: '/registration/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationDealershipRoute = RegistrationDealershipRouteImport.update({
  id: '/registration/dealership',
  path: '/registration/dealership',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationCompleteRoute = RegistrationCompleteRouteImport.update({
  id: '/registration/complete',
  path: '/registration/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordForgotRoute = PasswordForgotRouteImport.update({
  id: '/password/forgot',
  path: '/password/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRepair_ordersRoute =
  AuthenticatedRepair_ordersRouteImport.update({
    id: '/repair_orders',
    path: '/repair_orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParts_ordersRoute =
  AuthenticatedParts_ordersRouteImport.update({
    id: '/parts_orders',
    path: '/parts_orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedRepair_ordersIdRoute =
  AuthenticatedRepair_ordersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedRepair_ordersRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminShopsRoute = AuthenticatedAdminShopsRouteImport.update({
  id: '/admin/shops',
  path: '/admin/shops',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminParts_ordersRoute =
  AuthenticatedAdminParts_ordersRouteImport.update({
    id: '/admin/parts_orders',
    path: '/admin/parts_orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDealershipsRoute =
  AuthenticatedAdminDealershipsRouteImport.update({
    id: '/admin/dealerships',
    path: '/admin/dealerships',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const PasswordResetIdGuidHashRoute = PasswordResetIdGuidHashRouteImport.update({
  id: '/password/reset/$id/$guid/$hash',
  path: '/password/reset/$id/$guid/$hash',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/clerk': typeof ClerkAuthenticatedRouteRoute
  '/registrationResult': typeof RegistrationResultRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/': typeof ClerkauthRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/parts_orders': typeof AuthenticatedParts_ordersRoute
  '/repair_orders': typeof AuthenticatedRepair_ordersRouteWithChildren
  '/password/forgot': typeof PasswordForgotRoute
  '/registration/complete': typeof RegistrationCompleteRoute
  '/registration/dealership': typeof RegistrationDealershipRoute
  '/registration/shop': typeof RegistrationShopRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/dealerships': typeof AuthenticatedAdminDealershipsRoute
  '/admin/parts_orders': typeof AuthenticatedAdminParts_ordersRoute
  '/admin/shops': typeof AuthenticatedAdminShopsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/repair_orders/$id': typeof AuthenticatedRepair_ordersIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/password/reset/$id/$guid/$hash': typeof PasswordResetIdGuidHashRoute
}
export interface FileRoutesByTo {
  '/registrationResult': typeof RegistrationResultRoute
  '/clerk': typeof ClerkAuthenticatedRouteRoute
  '/login': typeof authLoginRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/parts_orders': typeof AuthenticatedParts_ordersRoute
  '/repair_orders': typeof AuthenticatedRepair_ordersRouteWithChildren
  '/password/forgot': typeof PasswordForgotRoute
  '/registration/complete': typeof RegistrationCompleteRoute
  '/registration/dealership': typeof RegistrationDealershipRoute
  '/registration/shop': typeof RegistrationShopRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/dealerships': typeof AuthenticatedAdminDealershipsRoute
  '/admin/parts_orders': typeof AuthenticatedAdminParts_ordersRoute
  '/admin/shops': typeof AuthenticatedAdminShopsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/repair_orders/$id': typeof AuthenticatedRepair_ordersIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/password/reset/$id/$guid/$hash': typeof PasswordResetIdGuidHashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/registrationResult': typeof RegistrationResultRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRoute
  '/(auth)/login': typeof authLoginRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/parts_orders': typeof AuthenticatedParts_ordersRoute
  '/_authenticated/repair_orders': typeof AuthenticatedRepair_ordersRouteWithChildren
  '/password/forgot': typeof PasswordForgotRoute
  '/registration/complete': typeof RegistrationCompleteRoute
  '/registration/dealership': typeof RegistrationDealershipRoute
  '/registration/shop': typeof RegistrationShopRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/dealerships': typeof AuthenticatedAdminDealershipsRoute
  '/_authenticated/admin/parts_orders': typeof AuthenticatedAdminParts_ordersRoute
  '/_authenticated/admin/shops': typeof AuthenticatedAdminShopsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/repair_orders/$id': typeof AuthenticatedRepair_ordersIdRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/password/reset/$id/$guid/$hash': typeof PasswordResetIdGuidHashRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/clerk'
    | '/registrationResult'
    | '/settings'
    | '/clerk/'
    | '/login'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/parts_orders'
    | '/repair_orders'
    | '/password/forgot'
    | '/registration/complete'
    | '/registration/dealership'
    | '/registration/shop'
    | '/'
    | '/admin/dealerships'
    | '/admin/parts_orders'
    | '/admin/shops'
    | '/admin/users'
    | '/errors/$error'
    | '/repair_orders/$id'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/help-center'
    | '/settings/'
    | '/tasks'
    | '/password/reset/$id/$guid/$hash'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/registrationResult'
    | '/clerk'
    | '/login'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/parts_orders'
    | '/repair_orders'
    | '/password/forgot'
    | '/registration/complete'
    | '/registration/dealership'
    | '/registration/shop'
    | '/'
    | '/admin/dealerships'
    | '/admin/parts_orders'
    | '/admin/shops'
    | '/admin/users'
    | '/errors/$error'
    | '/repair_orders/$id'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/help-center'
    | '/settings'
    | '/tasks'
    | '/password/reset/$id/$guid/$hash'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/registrationResult'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/login'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/parts_orders'
    | '/_authenticated/repair_orders'
    | '/password/forgot'
    | '/registration/complete'
    | '/registration/dealership'
    | '/registration/shop'
    | '/_authenticated/'
    | '/_authenticated/admin/dealerships'
    | '/_authenticated/admin/parts_orders'
    | '/_authenticated/admin/shops'
    | '/_authenticated/admin/users'
    | '/_authenticated/errors/$error'
    | '/_authenticated/repair_orders/$id'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/_authenticated/help-center/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/password/reset/$id/$guid/$hash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  RegistrationResultRoute: typeof RegistrationResultRoute
  authLoginRoute: typeof authLoginRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  PasswordForgotRoute: typeof PasswordForgotRoute
  RegistrationCompleteRoute: typeof RegistrationCompleteRoute
  RegistrationDealershipRoute: typeof RegistrationDealershipRoute
  RegistrationShopRoute: typeof RegistrationShopRoute
  PasswordResetIdGuidHashRoute: typeof PasswordResetIdGuidHashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registrationResult': {
      id: '/registrationResult'
      path: '/registrationResult'
      fullPath: '/registrationResult'
      preLoaderRoute: typeof RegistrationResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/registration/shop': {
      id: '/registration/shop'
      path: '/registration/shop'
      fullPath: '/registration/shop'
      preLoaderRoute: typeof RegistrationShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration/dealership': {
      id: '/registration/dealership'
      path: '/registration/dealership'
      fullPath: '/registration/dealership'
      preLoaderRoute: typeof RegistrationDealershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration/complete': {
      id: '/registration/complete'
      path: '/registration/complete'
      fullPath: '/registration/complete'
      preLoaderRoute: typeof RegistrationCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password/forgot': {
      id: '/password/forgot'
      path: '/password/forgot'
      fullPath: '/password/forgot'
      preLoaderRoute: typeof PasswordForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/repair_orders': {
      id: '/_authenticated/repair_orders'
      path: '/repair_orders'
      fullPath: '/repair_orders'
      preLoaderRoute: typeof AuthenticatedRepair_ordersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parts_orders': {
      id: '/_authenticated/parts_orders'
      path: '/parts_orders'
      fullPath: '/parts_orders'
      preLoaderRoute: typeof AuthenticatedParts_ordersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: '/'
      fullPath: '/clerk/'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/repair_orders/$id': {
      id: '/_authenticated/repair_orders/$id'
      path: '/$id'
      fullPath: '/repair_orders/$id'
      preLoaderRoute: typeof AuthenticatedRepair_ordersIdRouteImport
      parentRoute: typeof AuthenticatedRepair_ordersRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/shops': {
      id: '/_authenticated/admin/shops'
      path: '/admin/shops'
      fullPath: '/admin/shops'
      preLoaderRoute: typeof AuthenticatedAdminShopsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/parts_orders': {
      id: '/_authenticated/admin/parts_orders'
      path: '/admin/parts_orders'
      fullPath: '/admin/parts_orders'
      preLoaderRoute: typeof AuthenticatedAdminParts_ordersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dealerships': {
      id: '/_authenticated/admin/dealerships'
      path: '/admin/dealerships'
      fullPath: '/admin/dealerships'
      preLoaderRoute: typeof AuthenticatedAdminDealershipsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/password/reset/$id/$guid/$hash': {
      id: '/password/reset/$id/$guid/$hash'
      path: '/password/reset/$id/$guid/$hash'
      fullPath: '/password/reset/$id/$guid/$hash'
      preLoaderRoute: typeof PasswordResetIdGuidHashRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRepair_ordersRouteChildren {
  AuthenticatedRepair_ordersIdRoute: typeof AuthenticatedRepair_ordersIdRoute
}

const AuthenticatedRepair_ordersRouteChildren: AuthenticatedRepair_ordersRouteChildren =
  {
    AuthenticatedRepair_ordersIdRoute: AuthenticatedRepair_ordersIdRoute,
  }

const AuthenticatedRepair_ordersRouteWithChildren =
  AuthenticatedRepair_ordersRoute._addFileChildren(
    AuthenticatedRepair_ordersRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedParts_ordersRoute: typeof AuthenticatedParts_ordersRoute
  AuthenticatedRepair_ordersRoute: typeof AuthenticatedRepair_ordersRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminDealershipsRoute: typeof AuthenticatedAdminDealershipsRoute
  AuthenticatedAdminParts_ordersRoute: typeof AuthenticatedAdminParts_ordersRoute
  AuthenticatedAdminShopsRoute: typeof AuthenticatedAdminShopsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedParts_ordersRoute: AuthenticatedParts_ordersRoute,
  AuthenticatedRepair_ordersRoute: AuthenticatedRepair_ordersRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminDealershipsRoute: AuthenticatedAdminDealershipsRoute,
  AuthenticatedAdminParts_ordersRoute: AuthenticatedAdminParts_ordersRoute,
  AuthenticatedAdminShopsRoute: AuthenticatedAdminShopsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRoute
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRoute,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  RegistrationResultRoute: RegistrationResultRoute,
  authLoginRoute: authLoginRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  PasswordForgotRoute: PasswordForgotRoute,
  RegistrationCompleteRoute: RegistrationCompleteRoute,
  RegistrationDealershipRoute: RegistrationDealershipRoute,
  RegistrationShopRoute: RegistrationShopRoute,
  PasswordResetIdGuidHashRoute: PasswordResetIdGuidHashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
